### ISSUE TITLE
Indicate video posts

### ISSUE THREAD

**Issue by olganovosad** [LaboratoryGA/socialfeed#10]
Hello,

Shall we indicate the video post somewhere on video thumbnail?

Currently, it's not clear that this is a video post.

![thumbnailvideo](https://cloud.githubusercontent.com/assets/8656805/7411824/99fd9060-ef33-11e4-891e-5edb8ca2ffe0.png)

Thank you.

**Comment by LaboratoryGA** [comment]
How would you expect it indicated?

**Comment by olganovosad** [comment]
I have attached an example:

![videothumbnails](https://cloud.githubusercontent.com/assets/8656805/7414943/b45feaba-ef4d-11e4-9edd-b27953b4606c.png)

Would it be possible to do it?

Thank you.

**Comment by LaboratoryGA** [comment]
I will have to research and see if FB includes a time marker in the feed

**Comment by LaboratoryGA** [comment]
Okay, so I can add in the little "play" icon, but the FB API doesn't supply us with the runtime of the video.

**Comment by LaboratoryGA** [comment]
Added play icon.
