### ISSUE TITLE
Shared FB posts - links are not clickable

### ISSUE THREAD

**Issue by olganovosad** [LaboratoryGA/socialfeed#11]
Hello,

If you share a post and there any tagged users or links, they are not clickable.

![sharedlinks](https://cloud.githubusercontent.com/assets/8656805/7411832/b8b69718-ef33-11e4-9b8e-bbd1ee772bae.png)

Thanks

**Comment by LaboratoryGA** [comment]
It was specifically stated in the project parameters that links should only be clickable if the API provides that functionality. FB does not.
