### ISSUE TITLE
"View post" is not redirecting user to the original post in FB

### ISSUE THREAD

**Issue by olganovosad** [LaboratoryGA/socialfeed#12]
Hello,

Clicking "View post" is not redirecting to the original post in FB. Sometimes it redirects to FB home page (this happens when I view post for video post), or sometimes it is redirecting user to the one of the images for shared albums (the main image, which is displaying in the component).

In all cases user should be redirected to the original post on the page you have set.

The page I'm using for FB testing: https://www.facebook.com/iriepixel

Please let me know if I'm missing something.

**Comment by LaboratoryGA** [comment]
FB doesn't actually send us the original post URL, so it has to be constructed.

**Comment by olganovosad** [comment]
Hi Nathan,

Is this issue you are going to work on or should it be closed?

Thank you.

**Comment by LaboratoryGA** [comment]
I don't know that there is anything I can do here - the only way to link back to the "original" article is by using the object ID as supplied to us by Facebook, and that is what we are currently using.
