### ISSUE TITLE
Shared content/ cover image are not displaying in the compoent

### ISSUE THREAD

**Issue by olganovosad** [LaboratoryGA/socialfeed#14]
Hello,

If you share an event or a content from another source to your page, which includes image, the image and shared content are not displaying in the component, just the description you have added.

![noimage1](https://cloud.githubusercontent.com/assets/8656805/7413422/aa60d15a-ef43-11e4-803b-454d5241a259.png)
![noimage](https://cloud.githubusercontent.com/assets/8656805/7413423/aa72fa1a-ef43-11e4-93f1-884bf6a7d359.png)

**Comment by LaboratoryGA** [comment]
Some research has revealed this has to do with the post type being "event", which I haven't catered for.

**Comment by LaboratoryGA** [comment]
Added image support for events.
