### ISSUE TITLE
Link is not displayed as in the actual post in Twitter

### ISSUE THREAD

**Issue by olganovosad** [LaboratoryGA/socialfeed#15]
Hello,

Shouldn't the links be displayed as they are displaying in the actual post?

Currently, the link is displayed as per screenshot below:

![linkstwitter](https://cloud.githubusercontent.com/assets/8656805/7413496/5fadf506-ef44-11e4-8baa-1959c2f53ea9.png)

**Comment by LaboratoryGA** [comment]
This is how the Twitter API sends it to us.
