### ISSUE TITLE
Invalid resource value - amend error message

### ISSUE THREAD

**Issue by olganovosad** [LaboratoryGA/socialfeed#3]
Hello,

If user has added user account to the resource rather than the page name, the following error message is displayed:

Critical Error: (#803) Cannot query users by their username (olia.novosad.18)

![fbuseraccount](https://cloud.githubusercontent.com/assets/8656805/7410021/1a95b6a0-ef23-11e4-8ecb-cb18a9e16676.png)

Please amend the error message so it's user-friednly. I have attached the example of the error message design we have across the system:

![exampleerrormessage](https://cloud.githubusercontent.com/assets/8656805/7410059/62eaa5fa-ef23-11e4-9f10-5d1f82a261d5.png)

**Comment by LaboratoryGA** [comment]
This actually won't ever be visible once the final version has been made. This is because querying the social media stream will actually happen as a background, so the above error message would never be visible.
