### ISSUE TITLE
Links in FB posts headers are not displaying for full words

### ISSUE THREAD

**Issue by olganovosad** [LaboratoryGA/socialfeed#5]
Hello,

The FB posts headers are displayed half linked. The hyperlink should display for full words if there are in the original post OR should the plain text be displayed if the hyperlink is not applied..

Please see screenshot:

![linksintitle](https://cloud.githubusercontent.com/assets/8656805/7410183/7091a298-ef24-11e4-8e25-c84eba1f61d9.png)

**Comment by LaboratoryGA** [comment]
What page are you using to produce this? I'm not able to immediately reproduce this behaviour.

**Comment by olganovosad** [comment]
The issue happening with the following page:

https://www.facebook.com/AlinaCraft.handmade

**Comment by LaboratoryGA** [comment]
I have a feeling this might be related to the odd character display as well. I'm beginning to suspect is a "multi-byte" issue. I will need to research this more.

**Comment by LaboratoryGA** [comment]
Added to correct project
