### ISSUE TITLE
Limit length for text content - the post header cannot be expanded

### ISSUE THREAD

**Issue by olganovosad** [LaboratoryGA/socialfeed#9]
Hello,

I have limited the length of text content. It seems to be applied for header as well and when I try to expand it, the full post herder is not displaying.

Should the limit be applied for header or just body?

Please see screenshot:

![characterllimit](https://cloud.githubusercontent.com/assets/8656805/7411526/ccbb12c8-ef30-11e4-9e91-e4028621d9d7.png)

**Comment by LaboratoryGA** [comment]
"title" should not be truncated.
